### ISSUE TITLE
Add selector in linstor-csi-controller StatefulSet if you're using apiVersion: apps/v1

### ISSUE THREAD

**Issue by andy812** [kvaps/kube-linstor#3]
https://github.com/kvaps/kube-linstor/blob/32e8dba489c0e82c4f114830f31929e5ea8728ca/helm/kube-linstor/templates/linstor-csi.yaml#L378
Add this:
```
  selector:
    matchLabels:
      app: {{ template "linstor.fullname" . }}-csi-controller
      role: linstor-csi
```
to fix "error validating data: ValidationError(StatefulSet.spec): missing required field "selector" in io.k8s.api.apps.v1.StatefulSetSpec"
