### ISSUE TITLE
drbd.conf created as dir instead of file?

### ISSUE THREAD

**Issue by joalmjoalm** [kvaps/kube-linstor#4]
linstor-satellite-5b5mz
linstor
192.168.1.143
Waiting: PodInitializing
0
52 minutes
Error: failed to start container "init": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/drbd.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/8f1475873fe30288ca159ba41aceff5a982cc8e99d0b2362d065c195b53d559b/merged\\\" at \\\"/var/lib/docker/overlay2/8f1475873fe30288ca159ba41aceff5a982cc8e99d0b2362d065c195b53d559b/merged/etc/drbd.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Back-off restarting failed container

**Comment by joalmjoalm** [comment]
I got it up and running by going into the hosts and replacing the drbd.conf directory with a drbd.conf file. 

sudo rmdir drbd.conf
sudo vi drbd.conf
sudo chmod 777 drbd.conf

I dont know what created the drbd.conf as directory instead of  file. Appreciate if you could take a look why its created as directory.
If I re-run the installation its still created as a dir.

Hope it will continue to work by manually changing it to a file.

**Comment by kvaps** [comment]
Hey, sorry I lost your question a little.
- Do you use latest chart from the master?
- What is your Kubernetes version?
- Could you check do you have `type: FileOrCreate` for etc-drbd-conf volume for linstor-satellite daemonset?
https://github.com/kvaps/kube-linstor/blob/bf2b2a6fdc0358bbd552ac6d77552733234ba070/helm/kube-linstor/templates/linstor-satellite.yaml#L114-L117

**Comment by joalmjoalm** [comment]
No, Im running chart from tag v1.1.2
Running Kubernetes v1.15.4 as containers with Rancher RKE
other versions;
Kernel Version:
4.15.0-65-generic
OS Image:
Ubuntu 18.04.3 LTS
Container Runtime Version:
docker://18.9.9
Kubelet Version:
v1.15.4
Kube-Proxy Version:
v1.15.4
Operating system:
linux
Architecture:
amd64

I have FileorCreate in the file for the satellite daemonset. Have tried to remove containers and removed unused volumes and re-run the install in order to get rid of old overlay2 volumes without success. Have not tried a completely new install.

after manually replacing drbd.conf dir with empty drbd.conf file on host the config data is inserted into the file and it seems to work.

**Comment by kvaps** [comment]
Unfortunately I can't reproduce this issue:
```
rm -rf /etc/drbd.conf
```
then newly created pod creating new `/etc/drbd.conf` file, but not a directory.

Could you try repeat this test?

**Comment by joalmjoalm** [comment]
after deleting the /etc/drbd.conf file the satellite re-created /etc/drbd.conf as directory.
I did my workaround after that; deleted the dir, created fast a file before the satellite created a directory.
Still had the error but after deleting the satellite-pod and the pod was re-created and there was an existing /etc/drbd.conf as file the satellite was up and running again.
maybe the error is bound to my installation and dangled volumes or similar even if I have tried to delete them. 
I could try complete rke kubernetes and docker reinstall but that would have to wait for a while.

**Comment by joalmjoalm** [comment]
attach some configs and logs/J
[logs-from-linstor-satellite-in-linstor-satellite-fhwpq.txt](https://github.com/kvaps/kube-linstor/files/3797374/logs-from-linstor-satellite-in-linstor-satellite-fhwpq.txt)
[daemon_set_satellite.txt](https://github.com/kvaps/kube-linstor/files/3797376/daemon_set_satellite.txt)
[satellite_pod.txt](https://github.com/kvaps/kube-linstor/files/3797377/satellite_pod.txt)

**Comment by kvaps** [comment]
Hmm, it looks like you have kubelet related problem. BTW I can't reproduce it.

Try to run the next pod:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: fileorcreate-test
spec:
  nodeName: 192.168.1.143
  volumes:
  - name: config
    hostPath:
      path: "/tmp/some.conf"
      type: FileOrCreate
  initContainers:
  - name: init
    image: alpine
    command: [ "/bin/sh", "-c", "echo 'Helo World!' > /etc/drbd.conf" ]
    volumeMounts:
    - name: config
      mountPath: "/tmp/some.conf"
  containers:
  - name: container
    image: alpine
    command: [ '/bin/sh', '-c', 'while true; do sleep 1; done' ]
    volumeMounts:
    - name: config
      mountPath: "/tmp/some.conf"
```

Then check **192.168.1.143** node **/tmp/some.conf** path, it should be file, not directory.
