### ISSUE TITLE
Using external Linstor controller/cluster

### ISSUE THREAD

**Issue by matjazp** [kvaps/kube-linstor#50]
Is it possible to use this Helm chart with an existing external Linstor controller/cluster? So not as a usual k8s hyper-converged configuration, but via diskless attachments. Or maybe even installing just Satellites on k8s nodes. 

According to Linbit's Docs you can do that with Piraeus (https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-kubernetes-deploy-external-controller), what about kube-linstor?

**Comment by kvaps** [comment]
Hi, I have not tested this configuration yet.
But you can try achieving this by disabling linstor-controller, and tls:

```yaml
controller:
  enabled: false
  ssl: false
```

and creating service like this:
```yaml
apiVersion: v1
kind: Service
metadata: 
  name: linstor-controller
  namespace: linstor
  annotations: 
    prometheus.io/path: /metrics?error_reports=false
    prometheus.io/port: "3370"
    prometheus.io/scrape: "true"
  labels: 
    app: linstor-controller
spec: 
  ports: 
  - name: restapi
    port: 3370
```

and enpoints pointing to your original linstor-controller:
```yaml

kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "linstor-controller"
subsets:
  - addresses:
    -  ip: "1.1.1.1"
    ports:
    - name: restapi
      port: 3370
```

alternatively you can use externalName service https://kubernetes.io/docs/concepts/services-networking/service/#externalname

Of course we can consider special setting for adding SSL-certificates for the linstor-controller to enable SSL and adding externalName service automatically.

Would you really need it?
